config/routes.rb
Money::Application.routes.draw do
  root :to => 'home#index'
  resources :users
  resources :amounts
  resources :additions
  resources :sessions, :only => [:new, :create, :destroy]
  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :additions
end

app/models/addition.rb
class Addition < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
  belongs_to :amount

  
  def payment(user,amount)
    if valid?
      customer = Stripe::Customer.retrieve(user.stripe_id)
      Stripe::Charge.create(:amount => amount.cents, :currency => "usd", :customer => customer.id)
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/models/amount.rb
class Amount < ActiveRecord::Base
  has_many :additions

  def dollar_value
    "$#{cents/100}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  attr_accessor :stripe_card_token
  before_save :update_stripe
  
  has_many :additions
  has_one :account
  
  def update_stripe
    if stripe_card_token.present?
      if stripe_id.nil?
        customer = Stripe::Customer.create(
          :description => email,
          :card => stripe_card_token
        )
#         self.last_4_digits = customer.active_card.last4
#         response = customer.update_subscription({:plan => "premium"})
      else
        customer = Stripe::Customer.retrieve(stripe_id)
        customer.card = stripe_card_token
        customer.save
#         self.last_4_digits = customer.active_card.last4
      end

      self.stripe_id = customer.id
      self.stripe_card_token = nil
#     elsif last_4_digits_changed?
#       self.last_4_digits = last_4_digits_was
#     end
    end
  end
end

app/controllers/additions_controller.rb
class AdditionsController < ApplicationController
  def new
#   account = Account.find(params[current_user.id])
    @user = current_user
    @addition = @user.account.additions.build
  end

  def create
    @addition = Addition.new(params[:addition])
    @user = current_user
    @amount = Amount.find(params[:addition][:amount_id])
    if @addition.payment(@user, @amount)
      redirect_to @user, :notice => "Thanks dawg"
    else
      render :new
    end
  end

  def show
    @addition = Addition.find(params[:id])
  end
  
  def index
    @user = current_user
    @additions = current_user.additions
  end
end

app/controllers/amounts_controller.rb
class AmountsController < ApplicationController
  def index
    @amounts = Amount.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @user = current_user
    else
      @user = User.new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    @user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if @user.nil?
      #create an error message and rerender signin form
      flash.now[:error] = "Invalid email/password"
      @title = "Sign in"
      render 'new'
    else
      #sign the user in and redirect to the user's show page.
      sign_in @user
      redirect_to @user
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.build_account
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/additions_helper.rb
module AdditionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/additions/_form.html.haml
=nested_form_for @addition do |f|
  -if @addition.errors.any?
    .error_messages
      %h2
        =pluralize(@addition.errors.count, "error")
        prohibited this addition from being saved:
      %ul
        -@addition.errors.full_messages.each do |msg|
          %li= msg
  =f.collection_select( :amount_id, Amount.all, :id, :dollar_value)
  =f.hidden_field :account_id
  .actions
    =f.submit "Put money in your account"

app/views/additions/_user_fields.html.haml
-if current_user
  =f.label 
  =f.text_field 
-else
  =f.fields_for :user
-if @addition.stripe_card_token.present?
  Credit card has been provided.
-else
  .field
    =label_tag :card_number, "Credit Card Number"
    =text_field_tag :card_number, nil,:name => nil
  .field
    =label_tag :card_code, "Security Code on Card (CVV)"
    =text_field_tag :card_code, nil, :name => nil
  .field
    =label_tag :card_month, "Card Expiration"
    =select_month nil, {:add_month_numbers => true}, {:name => nil, :id => "card_month"}
    =select_year nil, {:start_year => Date.today.year, :end_year => Date.today.year+15}, {:name => nil, :id => "card_year"}
#stripe_error
  %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.

app/views/additions/edit.html.erb
<h1>Editing addition</h1>

<%= render 'form' %>

<%= link_to 'Show', @addition %> |
<%= link_to 'Back', additions_path %>

app/views/additions/index.html.erb
<h1>Listing additions</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>User</th>
    <th>Stripe customer token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @additions.each do |addition| %>
  <tr>
    <td><%= addition.amount_id %></td>
    <td><%= addition.user_id %></td>
    <td><%= addition.stripe_customer_token %></td>
    <td><%= link_to 'Show', addition %></td>
    <td><%= link_to 'Edit', edit_addition_path(addition) %></td>
    <td><%= link_to 'Destroy', addition, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Addition', new_addition_path %>

app/views/additions/new.html.erb
<h1>New addition</h1>

<%= render 'form' %>

<%= link_to 'Back', additions_path %>

app/views/additions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @addition.amount_id %>
</p>

<p>
  <b>User:</b>
  <%= @addition.user_id %>
</p>

<p>
  <b>Stripe customer token:</b>
  <%= @addition.stripe_customer_token %>
</p>


<%= link_to 'Edit', edit_addition_path(@addition) %> |
<%= link_to 'Back', additions_path %>

app/views/amounts/index.html.haml
=@amounts.each do |x|
  %p "#{x.cents}"

app/views/home/index.html.haml
=render 'users/form'
=render 'sessions/form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Money</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>
<%= render "shared/header" %>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.haml
-if target.errors.any? 
  #errorExplanation  
    %h2= "#{pluralize(target.errors.count, "error")} prohibited this from working:"  
    %ul 
      -target.errors.full_messages.each do |msg|  
        %li= msg

app/views/shared/_header.html.haml
%nav
	%ul		
		-if signed_in?			
			%li= link_to "home", user_path(current_user)
			%li= link_to "sign out", signout_path
		-else
			%li= link_to "sign in", signin_path

app/views/users/_form.html.haml
-if 
  %h1 Sign up
-else
  %h1 Edit
=form_for(@user) do |f|
  =render "shared/error_messages", :target => @user
  =f.hidden_field :stripe_card_token
  %dl
    %dt.field=f.label :name
    %dd.field=f.text_field :name
    %dt.field=f.label :email
    %dd.field=f.text_field :email
    -if @user.new_record?
      %dt.field=f.label :password
      %dd.field=f.password_field :password
    -if @user.stripe_card_token.present?
      Credit card has been provided.
    -else
      .field
        =label_tag :card_number, "Credit Card Number"
        =text_field_tag :card_number, nil,:name => nil
      .field
        =label_tag :card_code, "Security Code on Card (CVV)"
        =text_field_tag :card_code, nil, :name => nil
      .field
        =label_tag :card_month, "Card Expiration"
        =select_month nil, {:add_month_numbers => true}, {:name => nil, :id => "card_month"}
        =select_year nil, {:start_year => Date.today.year, :end_year => Date.today.year+15}, {:name => nil, :id => "card_year"}
      #stripe_error
      %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
  .actions
    =f.submit( "Sign Up")

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.haml
=render 'form'

app/views/users/show.html.haml
%p#notice= notice
%p
  %b Email:
  = @user.email
%p
  %b Name:
  = @user.name
  =@user.account.additions.each do  |x|
    %p=x.cents
= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', users_path}
=link_to 'Add money', new_addition_path(@user)
/=link_to 'look at your account', accounts_path(@user)